default:
  image:
    name: ubuntu:20.04
    entrypoint: ["/usr/bin/env"]

  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt -y update
    - apt -y upgrade
    - apt -y install texlive-latex-extra cm-super dvipng
    - apt -y install apt-utils net-tools python3.8 python3-venv python3-pip git curl g++ libboost-all-dev libgsl-dev libhdf5-serial-dev
    - curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
    - export WD=`pwd`
    - git clone https://github.com/TeamCOMPAS/COMPAS.git
    - cd COMPAS
    - export COMPAS_ROOT_DIR=`pwd`
    - cd src
    - make -f Makefile
    - cd $WD

django-tests:
  stage: test
  script:
    - cd src/
    - pip3 install -r requirements.txt
    - python3 development-manage.py jenkins --enable-coverage --coverage-rcfile=.coveragerc

  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: src/reports/coverage.xml
      junit: src/reports/junit.xml


npm-tests:
  stage: test
  script:
    - cd src/
    - pip3 install -r requirements.txt
    - python3 development-manage.py graphql_schema
    - cd react/
    - export NVM_DIR="$HOME/.nvm" && . "$NVM_DIR/nvm.sh" --no-use
    - eval "[ -f .nvmrc ] && nvm install && nvm use && nvm install-latest-npm"
    - npm install
    - npm run relay
    - npm run test-ci

  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: src/react/coverage/cobertura-coverage.xml
      junit: src/react/junit.xml


code-quality:
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
    SP_VERSION: 0.85.29
  allow_failure: true
  services:
    - docker:stable-dind
  before_script: []
  script:
    - docker run
        --env SOURCE_CODE="$PWD"
        --volume "$PWD":/code
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/ci-cd/codequality:$SP_VERSION" /code
  artifacts:
    reports:
      codequality: gl-code-quality-report.json


flake8:
  script:
    - pip3 install flake8-gl-codeclimate
    - flake8 --exit-zero --format gl-codeclimate --output-file gl-code-quality-report.json src/
  artifacts:
    reports:
      codequality: gl-code-quality-report.json

bundle-tests:
  stage: test
  script:
    - cd src/bundle/
    - python3 -m venv venv
    - . venv/bin/activate; pip install -r requirements.txt
    - . venv/bin/activate; coverage run -m xmlrunner discover --output-file ./junit.xml
    - . venv/bin/activate; coverage xml

  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: src/bundle/coverage.xml
      junit: src/bundle/junit.xml

