default:
  image:
    name: ubuntu:24.04
    entrypoint: ["/usr/bin/env"]

  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt -y update
    - apt -y upgrade
    - apt -y install python3.12 virtualenv python3-pip git curl 
    - curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
    - virtualenv -p3.12 venv
    - . venv/bin/activate
    - pip install -r src/requirements.txt
    - mkdir -p src/files/upload
    - export WD=`pwd`
    - git clone https://github.com/TeamCOMPAS/COMPAS.git
    - cd COMPAS
    - pip install .
    - cd $WD

django-tests:
  stage: test
  script:
    - cd $WD/src
    - python3 development-manage.py jenkins --enable-coverage --coverage-rcfile=.coveragerc

  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: src/reports/coverage.xml
      junit: src/reports/junit.xml


npm-tests:
  stage: test
  script:
    - cd $WD/src/
    - python3 development-manage.py graphql_schema
    - cd react/
    - export NVM_DIR="$HOME/.nvm" && . "$NVM_DIR/nvm.sh" --no-use
    - eval "[ -f .nvmrc ] && nvm install && nvm use && nvm install-latest-npm"
    - npm install --legacy-peer-deps
    - npm run relay
    - npm run test-ci

  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: src/react/coverage/cobertura-coverage.xml
      junit: src/react/junit.xml


code-quality:
  image: docker:25
  variables:
    DOCKER_DRIVER: overlay2
    SP_VERSION: 0.85.26
  allow_failure: true
  services:
    - docker:25-dind
  before_script: []
  script:
    - docker run
        --env SOURCE_CODE="$PWD"
        --volume "$PWD":/code
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/ci-cd/codequality:$SP_VERSION" /code
  artifacts:
    reports:
      codequality: gl-code-quality-report.json


flake8:
  script:
    - pip install flake8-gl-codeclimate
    - flake8 --exit-zero --format gl-codeclimate --output-file gl-code-quality-report.json src/
  artifacts:
    reports:
      codequality: gl-code-quality-report.json


black-check:
  stage: test
  script:
    - black --check src/
