version: "3"

services:
  gwlandscape-compas-django:
    build:
      dockerfile: ./docker/gwlandscape_compas_django.Dockerfile
      context: .
    image: nexus.gwdc.org.au/docker/gwlandscape_compas_django:0.34
    env_file: 
      - ".env"
      - ".env.production"
    volumes:
      - media_files:/files/
    ports:
      - "8000"
    depends_on:
      - db
      - gwlandscape-compas-redis
    restart: always

  gwlandscape-compas-nginx:
    build:
      dockerfile: ./docker/gwlandscape_compas_nginx.Dockerfile
      context: .
    image: nexus.gwdc.org.au/docker/gwlandscape_compas_nginx:0.5
    ports:
      - "8000:8000"
    depends_on:
      - gwlandscape-compas-static
      - gwlandscape-compas-django
    volumes:
      - media_files:/files/
    restart: always

  gwlandscape-compas-static:
    build:
      dockerfile: ./docker/gwlandscape_compas_static.Dockerfile
      context: .
    image: nexus.gwdc.org.au/docker/gwlandscape_compas_static:0.26
    ports:
      - "8000"
    restart: always

  db:
    image: mysql:5.7
    env_file: 
      - ".env"
      - ".env.production"
    volumes:
      - var_lib_mysql:/var/lib/mysql
    restart: always

  gwlandscape-compas-redis:
    image: redis:latest
    ports:
      - "6379"
    restart: always

  gwlandscape-compas-celery:
    build:
      context: .
      dockerfile: ./docker/gwlandscape_compas_celery.Dockerfile
    image: nexus.gwdc.org.au/docker/gwlandscape_compas_celery:0.14
    restart: always
    env_file: 
      - ".env"
      - ".env.production"
    volumes:
      - media_files:/files/
    depends_on:
      - gwlandscape-compas-redis
      - gwlandscape-compas-django

volumes:
  var_lib_mysql:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data/mysql
  media_files:
    # Comment the following block if using this locally
    driver_opts:
      o: bind
      type: none
      device: /mnt/oz324
