version: "3"

services:
  gwlandscape-compas-django:
    build:
      dockerfile: ./docker/gwlandscape_compas_django.Dockerfile
      context: .
    image: nexus.gwdc.org.au/docker/gwlandscape_compas_django:0.25
    environment:
      MYSQL_ROOT_PASSWORD: 76vcqmGKP19Z1AEx
      MYSQL_DATABASE: gwlandscape_compas
      MYSQL_USER: django
      MYSQL_PASSWORD: 76vcqmGKP19Z1AEx
      MYSQL_HOST: db
      PERMITTED_PUBLICATION_MANAGEMENT_USER_IDS: "[]"
      SECRET_KEY: "super_secret"
    volumes:
      - media_files:/files/
    ports:
      - "8000"
    depends_on:
      - db
      - gwlandscape-compas-redis

  gwlandscape-compas-nginx:
    build:
      dockerfile: ./docker/gwlandscape_compas_nginx.Dockerfile
      context: .
    image: nexus.gwdc.org.au/docker/gwlandscape_compas_nginx:0.4
    ports:
      - "8000:8000"
    depends_on:
      - gwlandscape-compas-static
      - gwlandscape-compas-django
    volumes:
      - media_files:/files/

  gwlandscape-compas-static:
    build:
      dockerfile: ./docker/gwlandscape_compas_static.Dockerfile
      context: .
    image: nexus.gwdc.org.au/docker/gwlandscape_compas_static:0.23
    ports:
      - "8000"

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 76vcqmGKP19Z1AEx
      MYSQL_DATABASE: gwlandscape_compas
      MYSQL_USER: django
      MYSQL_PASSWORD: 76vcqmGKP19Z1AEx
    volumes:
      - var_lib_mysql:/var/lib/mysql

  gwlandscape-compas-redis:
    image: redis:latest
    ports:
      - "6379"

  gwlandscape-compas-celery:
    build:
      context: .
      dockerfile: ./docker/gwlandscape_compas_celery.Dockerfile
    image: nexus.gwdc.org.au/docker/gwlandscape_compas_celery:0.11
    restart: always
    environment:
      PERMITTED_PUBLICATION_MANAGEMENT_USER_IDS: "[]"
      SECRET_KEY: "super_secret"
    volumes:
      - media_files:/files/
    depends_on:
      - gwlandscape-compas-redis
      - gwlandscape-compas-django

volumes:
  var_lib_mysql:
  media_files:
