version: '3'

services:
  django:
    build:
      dockerfile: ./docker/gwlandscape_compas_django.Dockerfile
      context: .
    image: nexus.gwdc.org.au/docker/gwlandscape_compas_django:0.2
    container_name: gwlandscape_compas_django
    environment:
      MYSQL_ROOT_PASSWORD: 76vcqmGKP19Z1AEx
      MYSQL_DATABASE: gwlandscape_compas
      MYSQL_USER: django
      MYSQL_PASSWORD: 76vcqmGKP19Z1AEx
      MYSQL_HOST: db
    ports:
      - "8000"
    depends_on:
      - db

  nginx:
    build:
      dockerfile: ./docker/gwlandscape_compas_nginx.Dockerfile
      context: .
    image: nexus.gwdc.org.au/docker/gwlandscape_compas_nginx:0.1
    container_name: gwlandscape_compas_nginx
    ports:
      - "8000:8000"
    depends_on:
      - static
      - django
      
  static:
    build:
      dockerfile: ./docker/gwlandscape_compas_static.Dockerfile
      context: .
    image: nexus.gwdc.org.au/docker/gwlandscape_compas_static:0.1
    container_name: gwlandscape_compas_static
    ports:
      - "8000"
      
  db:
    image: mysql:5.7
    container_name: gwlandscape_compas_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 76vcqmGKP19Z1AEx
      MYSQL_DATABASE: gwlandscape_compas
      MYSQL_USER: django
      MYSQL_PASSWORD: 76vcqmGKP19Z1AEx
    volumes:
      - var_lib_mysql:/var/lib/mysql
  
volumes:
  var_lib_mysql:
