# Generated by Django 2.2.16 on 2021-11-22 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compasui", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SingleBinaryJob",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mass1",
                    models.FloatField(
                        default=35.4,
                        help_text="Mass of the initially more massive star.  0 < Value < 150",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(150.0),
                        ],
                    ),
                ),
                (
                    "mass2",
                    models.FloatField(
                        default=31.3,
                        help_text="Mass of the initially less massive star. 0 < Value < 150",
                        validators=[
                            django.core.validators.MinValueValidator(0.1),
                            django.core.validators.MaxValueValidator(150.0),
                        ],
                    ),
                ),
                (
                    "metallicity",
                    models.FloatField(
                        default=0.001,
                        help_text="Metallicity of stars.  1E-4 < Value < 0.03",
                        validators=[
                            django.core.validators.MinValueValidator(0.0001),
                            django.core.validators.MaxValueValidator(0.03),
                        ],
                    ),
                ),
                (
                    "eccentricity",
                    models.FloatField(
                        default=0.0,
                        help_text="Orbital eccentricity of the binary. 0 <= Value < 1",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "separation",
                    models.FloatField(
                        blank=True,
                        default=1.02,
                        help_text="Value > 0",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "orbital_period",
                    models.FloatField(
                        blank=True,
                        help_text="Value > 0",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
            ],
        ),
    ]
