# Generated by Django 2.2.16 on 2021-11-22 23:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compasui", "0002_singlebinaryjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="singlebinaryjob",
            name="max_time",
            field=models.FloatField(
                blank=True,
                default=0,
                help_text="Maximum time to evolve binary for. 0 < Value <= 1400",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1400),
                ],
            ),
        ),
    ]
