# Generated by Django 2.2.16 on 2021-11-22 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("compasui", "0003_singlebinaryjob_max_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="singlebinaryjob",
            name="max_time",
        ),
    ]
