# Generated by Django 2.2.16 on 2022-02-01 02:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasui', '0004_remove_singlebinaryjob_max_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlebinaryjob',
            name='mean_anomaly_1',
            field=models.FloatField(blank=True, help_text='--kick-mean-anomaly-1: The mean anomaly at the instant of the supernova for the primary star of a binary system when evolving in BSE mode, should it undergo a supernova event, 0 < Value < 2pi', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(6.283185307179586)]),
        ),
        migrations.AddField(
            model_name='singlebinaryjob',
            name='mean_anomaly_2',
            field=models.FloatField(blank=True, help_text='--kick-mean-anomaly-2: The mean anomaly at the instant of the supernova for the secondary star of a binary system when evolving in BSE mode, should it undergo a supernova event, 0 < Value < 2pi', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(6.283185307179586)]),
        ),
        migrations.AddField(
            model_name='singlebinaryjob',
            name='phi_1',
            field=models.FloatField(blank=True, help_text='--kick-phi-1: The angle between ’x’ and ’y’, both in the orbital plane of the supernova vector, for the for the primary star of a binary system when evolving in BSE mode, should it undergo a supernova event (radians), 0 < Value < 2pi', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(6.283185307179586)]),
        ),
        migrations.AddField(
            model_name='singlebinaryjob',
            name='phi_2',
            field=models.FloatField(blank=True, help_text='--kick-phi-2: The angle between ’x’ and ’y’, both in the orbital plane of the supernova vector, for the for the seocndary star of a binary system when evolving in BSE mode, should it undergo a supernova event (radians), 0 < Value < 2pi', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(6.283185307179586)]),
        ),
        migrations.AddField(
            model_name='singlebinaryjob',
            name='theta_1',
            field=models.FloatField(blank=True, help_text='--kick-theta-1: The angle between the orbital plane and the ’z’ axis of the supernova vector for the for the primary star of a binary system when evolving in BSE mode, should it undergo a supernova event (radians), 0 < Value < 2pi', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(6.283185307179586)]),
        ),
        migrations.AddField(
            model_name='singlebinaryjob',
            name='theta_2',
            field=models.FloatField(blank=True, help_text='--kick-theta-2: The angle between the orbital plane and the ’z’ axis of the supernova vector for the for the secondary star of a binary system when evolving in BSE mode, should it undergo a supernova event (radians), 0 < Value < 2pi', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(6.283185307179586)]),
        ),
        migrations.AddField(
            model_name='singlebinaryjob',
            name='velocity_1',
            field=models.FloatField(blank=True, default=0.0, help_text='--kick-magnitude-1(Velocity1): Value to be used as the (drawn) kick magnitude for the primary star of a binary system when evolving in BSE mode, should the star undergo a supernova event (km s −1 ), Value > 0', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='singlebinaryjob',
            name='velocity_2',
            field=models.FloatField(blank=True, default=0.0, help_text='--kick-magnitude-2(Velocity2): Value to be used as the (drawn) kick magnitude for the secondary star of a binary system when evolving in BSE mode, should the star undergo a supernova event (km s −1 ), Value > 0', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='singlebinaryjob',
            name='velocity_random_number_1',
            field=models.FloatField(blank=True, help_text='--kick-magnitude-random-1: Value to be used to draw the kick magnitude for the primary star of a binary system when evolving in BSE mode, should the star undergo a supernova event, 0 < Value < 1', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='singlebinaryjob',
            name='velocity_random_number_2',
            field=models.FloatField(blank=True, help_text='--kick-magnitude-random-2: Value to be used to draw the kick magnitude for the secondary star of a binary system when evolving in BSE mode, should the star undergo a supernova event, 0 < Value < 1', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
