# Generated by Django 2.2.16 on 2022-02-09 06:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compasui", "0006_auto_20220208_0032"),
    ]

    operations = [
        migrations.AddField(
            model_name="singlebinaryjob",
            name="Kick_velocity_distribution",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ZERO", "ZERO"),
                    ("FIXED", "FIXED"),
                    ("FLAT", "FLAT"),
                    ("MAXWELLIAN", "MAXWELLIAN"),
                    ("BRAYELDRIDGE", "BRAYELDRIDGE"),
                    ("MULLER2016", "MULLER2016"),
                    ("MULLER2016MAXWELLIAN", "MULLER2016MAXWELLIAN"),
                    ("MULLERMANDEL", "MULLERMANDEL"),
                ],
                default="MAXWELLIAN",
                help_text="--kick-magnitude-distribution: Natal kick magnitude distribution",
                max_length=55,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="singlebinaryjob",
            name="black_hole_kicks",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FALLBACK", "FALLBACK"),
                    ("FULL", "FULL"),
                    ("REDUCED", "REDUCED"),
                    ("ZERO", "ZERO"),
                ],
                default="FALLBACK",
                help_text="--black-hole-kicks: Black hole kicks relative to NS kicks",
                max_length=55,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="singlebinaryjob",
            name="fryer_supernova_engine",
            field=models.CharField(
                blank=True,
                choices=[("DELAYED", "DELAYED"), ("RAPID", "RAPID")],
                default="DELAYED",
                help_text="--fryer-supernova-engine: Supernova engine type if using the fallback prescription from Fryer et al. (2012)",
                max_length=55,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="singlebinaryjob",
            name="kick_velocity_sigma_CCSN_BH",
            field=models.FloatField(
                blank=True,
                default=256.0,
                help_text="--kick-magnitude-sigma-CCSN-BH: Sigma for chosen kick magnitude distribution for black holes (km s − 1 ), Value > 0",
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="singlebinaryjob",
            name="kick_velocity_sigma_CCSN_NS",
            field=models.FloatField(
                blank=True,
                default=250.0,
                help_text="--kick-magnitude-sigma-CCSN-NS: Sigma for chosen kick magnitude distribution for neutron stars (km s − 1 ), Value > 0",
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="singlebinaryjob",
            name="kick_velocity_sigma_ECSN",
            field=models.FloatField(
                blank=True,
                default=30.0,
                help_text="--kick-magnitude-sigma-ECSN: Sigma for chosen kick magnitude distribution for ECSN (km s − 1 ), Value > 0",
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="singlebinaryjob",
            name="kick_velocity_sigma_USSN",
            field=models.FloatField(
                blank=True,
                default=30.0,
                help_text="--kick-magnitude-sigma-USSN: Sigma for chosen kick magnitude distribution for USSN (km s − 1 ), Value > 0",
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="singlebinaryjob",
            name="maximum_neutron_star_mass",
            field=models.FloatField(
                blank=True,
                default=3.0,
                help_text="--maximum-neutron-star-mass: Maximum mass of a neutron star, Value > 0",
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="singlebinaryjob",
            name="pair_instability_supernovae",
            field=models.BooleanField(
                default=True,
                help_text="--pair-instability-supernovae: Enable pair instability supernovae (PISN)",
            ),
        ),
        migrations.AddField(
            model_name="singlebinaryjob",
            name="pisn_lower_limit",
            field=models.FloatField(
                blank=True,
                default=60.0,
                help_text="--pisn-lower-limit: Minimum core mass for PISN, Value > 0",
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="singlebinaryjob",
            name="pisn_upper_limit",
            field=models.FloatField(
                blank=True,
                default=135.0,
                help_text="--pisn-upper-limit: Maximum core mass for PISN, 0 < Value >  --pisn-lower-limit",
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="singlebinaryjob",
            name="ppi_lower_limit",
            field=models.FloatField(
                blank=True,
                default=35.0,
                help_text="--pisn-lower-limit: Minimum core mass for PPI, Value > 0",
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="singlebinaryjob",
            name="ppi_upper_limit",
            field=models.FloatField(
                blank=True,
                default=60.0,
                help_text="--pisn-upper-limit: Maximum core mass for PPI, 0 < Value > --pisn-lower-limit",
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="singlebinaryjob",
            name="pulsational_pair_instability_prescription",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COMPAS", "COMPAS"),
                    ("STARTRACK", "STARTRACK"),
                    ("MARCHANT", "MARCHANT"),
                ],
                default="MARCHANT",
                help_text="--pulsational-pair-instability-prescription: Pulsational pair instability prescription",
                max_length=55,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="singlebinaryjob",
            name="pulsational_pair_instability_supernovae",
            field=models.BooleanField(
                default=True,
                help_text="--pulsational-pair-instability: Enable mass loss due to pulsational-pair-instability (PPI)",
            ),
        ),
        migrations.AddField(
            model_name="singlebinaryjob",
            name="remnant_mass_prescription",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HURLEY2000", "HURLEY2000"),
                    ("BELCZYNSKI2002", "BELCZYNSKI2002"),
                    ("FRYER2012", "FRYER2012"),
                    ("MULLER2016", "MULLER2016"),
                    ("MULLERMANDEL", "MULLERMANDEL"),
                ],
                default="FRYER2012",
                help_text="--remnant-mass-prescription: Remnant mass prescription",
                max_length=55,
                null=True,
            ),
        ),
    ]
