# Generated by Django 3.2.13 on 2022-06-09 04:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasui', '0013_auto_20220210_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlebinaryjob',
            name='mass_transfer_accertion_efficiency_prescription',
        ),
        migrations.AddField(
            model_name='singlebinaryjob',
            name='mass_transfer_accretion_efficiency_prescription',
            field=models.CharField(blank=True, choices=[('THERMAL', 'THERMAL'), ('FIXED', 'FIXED')], default='THERMAL', help_text='--mass-transfer-accretion-efficiency-prescription:         Mass transfer accretion efficiency prescription', max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='singlebinaryjob',
            name='fryer_supernova_engine',
            field=models.CharField(blank=True, choices=[('DELAYED', 'DELAYED'), ('RAPID', 'RAPID')], default='DELAYED', help_text='--fryer-supernova-engine: Supernova engine type if using         the fallback prescription from Fryer et al. (2012)', max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='singlebinaryjob',
            name='kick_velocity_sigma_CCSN_BH',
            field=models.FloatField(blank=True, default=256.0, help_text='--kick-magnitude-sigma-CCSN-BH: Sigma for chosen kick magnitude         distribution for black holes (km s − 1 ), Value > 0', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='singlebinaryjob',
            name='kick_velocity_sigma_CCSN_NS',
            field=models.FloatField(blank=True, default=250.0, help_text='--kick-magnitude-sigma-CCSN-NS: Sigma for chosen kick magnitude         distribution for neutron stars (km s − 1 ), Value > 0', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='singlebinaryjob',
            name='kick_velocity_sigma_ECSN',
            field=models.FloatField(blank=True, default=30.0, help_text='--kick-magnitude-sigma-ECSN: Sigma for chosen kick magnitude         distribution for ECSN (km s − 1 ), Value > 0', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='singlebinaryjob',
            name='kick_velocity_sigma_USSN',
            field=models.FloatField(blank=True, default=30.0, help_text='--kick-magnitude-sigma-USSN: Sigma for chosen kick magnitude         distribution for USSN (km s − 1 ), Value > 0', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='singlebinaryjob',
            name='mass1',
            field=models.FloatField(default=35.0, help_text='Mass of the initially more massive star.  0 < Value < 150', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(150.0)]),
        ),
        migrations.AlterField(
            model_name='singlebinaryjob',
            name='mass2',
            field=models.FloatField(default=31.0, help_text='Mass of the initially less massive star. 0 < Value < 150', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(150.0)]),
        ),
        migrations.AlterField(
            model_name='singlebinaryjob',
            name='mass_transfer_angular_momentum_loss_prescription',
            field=models.CharField(blank=True, choices=[('ARBITRARY', 'ARBITRARY'), ('ISOTROPIC', 'ISOTROPIC'), ('JEANS', 'JEANS'), ('CIRCUMBINARY', 'CIRCUMBINARY')], default='ISOTROPIC', help_text='--mass-transfer-angular-momentum-loss-prescription:         Mass Transfer Angular Momentum Loss prescription', max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='singlebinaryjob',
            name='mass_transfer_fa',
            field=models.FloatField(blank=True, default=0.5, help_text='--mass-transfer-fa: Mass Transfer fraction accreted         in FIXED prescription', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='singlebinaryjob',
            name='mass_transfer_jloss',
            field=models.FloatField(blank=True, default=1.0, help_text='--mass-transfer-jloss: Specific angular         momentum with which the non-accreted system leaves the system', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='singlebinaryjob',
            name='mean_anomaly_1',
            field=models.FloatField(blank=True, help_text='--kick-mean-anomaly-1: The mean anomaly at the instant of the         supernova for the primary star of a binary system when evolving in BSE mode,         should it undergo a supernova event, 0 < Value < 2pi', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(6.283185307179586)]),
        ),
        migrations.AlterField(
            model_name='singlebinaryjob',
            name='mean_anomaly_2',
            field=models.FloatField(blank=True, help_text='--kick-mean-anomaly-2: The mean anomaly at the instant of the supernova         for the secondary star of a binary system when evolving in BSE mode, should it         undergo a supernova event, 0 < Value < 2pi', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(6.283185307179586)]),
        ),
        migrations.AlterField(
            model_name='singlebinaryjob',
            name='phi_1',
            field=models.FloatField(blank=True, help_text='--kick-phi-1: The angle between ’x’ and ’y’, both in the orbital         plane of the supernova vector, for the for the primary star of a binary system         when evolving in BSE mode, should it undergo a supernova event (radians), 0 < Value < 2pi', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(6.283185307179586)]),
        ),
        migrations.AlterField(
            model_name='singlebinaryjob',
            name='phi_2',
            field=models.FloatField(blank=True, help_text='--kick-phi-2: The angle between ’x’ and ’y’, both in the         orbital plane of the supernova vector, for the for the seocndary star         of a binary system when evolving in BSE mode, should it undergo a         supernova event (radians), 0 < Value < 2pi', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(6.283185307179586)]),
        ),
        migrations.AlterField(
            model_name='singlebinaryjob',
            name='pisn_upper_limit',
            field=models.FloatField(blank=True, default=135.0, help_text='--pisn-upper-limit: Maximum core mass for PISN,         0 < Value >  --pisn-lower-limit', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='singlebinaryjob',
            name='ppi_upper_limit',
            field=models.FloatField(blank=True, default=60.0, help_text='--pisn-upper-limit: Maximum core mass for PPI,         0 < Value > --pisn-lower-limit', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='singlebinaryjob',
            name='pulsational_pair_instability_prescription',
            field=models.CharField(blank=True, choices=[('COMPAS', 'COMPAS'), ('STARTRACK', 'STARTRACK'), ('MARCHANT', 'MARCHANT')], default='MARCHANT', help_text='--pulsational-pair-instability-prescription:         Pulsational pair instability prescription', max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='singlebinaryjob',
            name='pulsational_pair_instability_supernovae',
            field=models.BooleanField(blank=True, help_text='--pulsational-pair-instability: Enable mass loss due to         pulsational-pair-instability (PPI)', null=True),
        ),
        migrations.AlterField(
            model_name='singlebinaryjob',
            name='theta_1',
            field=models.FloatField(blank=True, help_text='--kick-theta-1: The angle between the orbital plane and the ’z’         axis of the supernova vector for the for the primary star of a binary system        when evolving in BSE mode, should it undergo a supernova event (radians),         0 < Value < 2pi', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(6.283185307179586)]),
        ),
        migrations.AlterField(
            model_name='singlebinaryjob',
            name='theta_2',
            field=models.FloatField(blank=True, help_text='--kick-theta-2: The angle between the orbital plane and the ’z’ axis         of the supernova vector for the for the secondary star of a binary system when          evolving in BSE mode, should it undergo a supernova event (radians),           0 < Value < 2pi', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(6.283185307179586)]),
        ),
        migrations.AlterField(
            model_name='singlebinaryjob',
            name='velocity_1',
            field=models.FloatField(blank=True, default=0.0, help_text='--kick-magnitude-1(Velocity1): Value to be used as the (drawn)         kick magnitude for the primary star of a binary system when evolving in          BSE mode, should the star undergo a supernova event (km s −1 ), Value > 0', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='singlebinaryjob',
            name='velocity_2',
            field=models.FloatField(blank=True, default=0.0, help_text='--kick-magnitude-2(Velocity2): Value to be used as the (drawn)         kick magnitude for the secondary star of a binary system when evolving          in BSE mode, should the star undergo a supernova event (km s −1 ), Value > 0', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='singlebinaryjob',
            name='velocity_random_number_1',
            field=models.FloatField(blank=True, help_text='--kick-magnitude-random-1: Value to be used to draw the         kick magnitude for the primary star of a binary system when evolving in BSE mode,        should the star undergo a supernova event, 0 < Value < 1', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='singlebinaryjob',
            name='velocity_random_number_2',
            field=models.FloatField(blank=True, help_text='--kick-magnitude-random-2: Value to be used to draw the kick         magnitude for the secondary star of a binary system when evolving in BSE mode,         should the star undergo a supernova event, 0 < Value < 1', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
