# Generated by Django 3.2.13 on 2022-11-22 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("compasui", "0015_auto_20220823_0631"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="singlebinaryjob",
            name="black_hole_kicks",
        ),
        migrations.RemoveField(
            model_name="singlebinaryjob",
            name="common_envelope_lambda",
        ),
        migrations.RemoveField(
            model_name="singlebinaryjob",
            name="kick_velocity_sigma_CCSN_BH",
        ),
        migrations.RemoveField(
            model_name="singlebinaryjob",
            name="kick_velocity_sigma_CCSN_NS",
        ),
        migrations.RemoveField(
            model_name="singlebinaryjob",
            name="kick_velocity_sigma_ECSN",
        ),
        migrations.RemoveField(
            model_name="singlebinaryjob",
            name="kick_velocity_sigma_USSN",
        ),
        migrations.RemoveField(
            model_name="singlebinaryjob",
            name="mass_transfer_jloss",
        ),
        migrations.RemoveField(
            model_name="singlebinaryjob",
            name="maximum_neutron_star_mass",
        ),
        migrations.RemoveField(
            model_name="singlebinaryjob",
            name="mean_anomaly_1",
        ),
        migrations.RemoveField(
            model_name="singlebinaryjob",
            name="mean_anomaly_2",
        ),
        migrations.RemoveField(
            model_name="singlebinaryjob",
            name="pair_instability_supernovae",
        ),
        migrations.RemoveField(
            model_name="singlebinaryjob",
            name="phi_1",
        ),
        migrations.RemoveField(
            model_name="singlebinaryjob",
            name="phi_2",
        ),
        migrations.RemoveField(
            model_name="singlebinaryjob",
            name="pisn_lower_limit",
        ),
        migrations.RemoveField(
            model_name="singlebinaryjob",
            name="pisn_upper_limit",
        ),
        migrations.RemoveField(
            model_name="singlebinaryjob",
            name="ppi_lower_limit",
        ),
        migrations.RemoveField(
            model_name="singlebinaryjob",
            name="ppi_upper_limit",
        ),
        migrations.RemoveField(
            model_name="singlebinaryjob",
            name="pulsational_pair_instability_prescription",
        ),
        migrations.RemoveField(
            model_name="singlebinaryjob",
            name="pulsational_pair_instability_supernovae",
        ),
        migrations.RemoveField(
            model_name="singlebinaryjob",
            name="theta_1",
        ),
        migrations.RemoveField(
            model_name="singlebinaryjob",
            name="theta_2",
        ),
        migrations.RemoveField(
            model_name="singlebinaryjob",
            name="velocity_random_number_1",
        ),
        migrations.RemoveField(
            model_name="singlebinaryjob",
            name="velocity_random_number_2",
        ),
    ]
