# Generated by Django 3.2.13 on 2023-08-14 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasui', '0017_filedownloadtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='compasjob',
            name='detailed_output',
            field=models.BooleanField(default=False),
        ),
    ]
