# Generated by Django 3.2.13 on 2023-05-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compasui', '0017_filedownloadtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compasjob',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
