# Generated by Django 3.2.13 on 2023-08-29 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compasui', '0018_compasjob_detailed_output'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compasjob',
            name='detailed_output',
        ),
    ]
