apiVersion: v1
kind: PersistentVolume
metadata:
  name: gwlandscape-compas-nfs-job-data-pv
  namespace: gwcloud
  labels:
    volume: gwlandscape-compas-nfs-job-data-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Ti
  nfs:
    server: 192.168.0.10
    path: "/lustre/oz324"
