apiVersion: v1
kind: Service
metadata:
  labels:
    name: gwlandscape-compas-redis
  name: gwlandscape-compas-redis
  namespace: gwcloud
spec:
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    name: gwlandscape-compas-redis
  sessionAffinity: None
  type: ClusterIP
