apiVersion: v1
kind: PersistentVolume
metadata:
  name: gwlandscape-compas-nfs-job-data-pv
  namespace: gwcloud
  labels:
    volume: gwlandscape-compas-nfs-job-data-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 256Gi
  nfs:
    server: 10.8.41.12
    path: "/mnt/sharedfolder/gwlandscape/compas/job_data"
