---
# 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gwlandscape-compas-redis
  namespace: gwcloud
  labels:
    name: gwlandscape-compas-redis
spec:
  replicas: 1
  selector:
    matchLabels:
        name: gwlandscape-compas-redis
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        name: gwlandscape-compas-redis
    spec:
      containers:
        - name: gwlandscape-compas-redis
          image: redis:latest
          ports:
            - name: redis
              containerPort: 6379
          resources: {}
          tty: true
      imagePullSecrets:
        - name: regcred
... 
