---
# 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gwlandscape-compas-celery
  namespace: gwcloud
  labels:
    name: gwlandscape-compas-celery
spec:
  replicas: 1
  selector:
    matchLabels:
        name: gwlandscape-compas-celery
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        name: gwlandscape-compas-celery
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: compas
            - secretRef:
                name: common
          name: gwlandscape-compas-celery
          image: nexus.gwdc.org.au/docker/gwlandscape_compas_celery:0.6
          resources:
            limits:
              cpu: "8000m"
              memory: "8192M"
            requests:
              cpu: "1000m"
              memory: "2048M"
          tty: true
          volumeMounts:
            - name: gwlandscape-compas-nfs-job-data
              mountPath: "/files/"
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: gwlandscape-compas-nfs-job-data
          persistentVolumeClaim:
            claimName: gwlandscape-compas-nfs-job-data-pvc
      nodeSelector:
        kubernetes.io/hostname: node7
... 
