# Generated by Django 2.2.16 on 2022-04-11 00:42

from django.db import migrations, models
import django.db.models.deletion
import publications.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompasDatasetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to=publications.models.job_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='CompasModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('summary', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('dataset_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.CompasDatasetModel')),
            ],
        ),
        migrations.CreateModel(
            name='CompasPublication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('published', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField(null=True)),
                ('journal', models.CharField(max_length=255, null=True)),
                ('journal_DOI', models.CharField(max_length=255, null=True)),
                ('dataset_DOI', models.CharField(max_length=255, null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('public', models.BooleanField(default=False)),
                ('download_link', models.TextField(blank=True, null=True)),
                ('arxiv_id', models.CharField(max_length=255)),
                ('keywords', models.ManyToManyField(to='publications.Keyword')),
            ],
        ),
        migrations.AddField(
            model_name='compasdatasetmodel',
            name='compas_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.CompasModel'),
        ),
        migrations.AddField(
            model_name='compasdatasetmodel',
            name='compas_publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.CompasPublication'),
        ),
    ]
