# Generated by Django 2.2.16 on 2022-04-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keyword",
            name="tag",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
