# Generated by Django 2.2.28 on 2022-05-16 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0003_auto_20220412_0908"),
    ]

    operations = [
        migrations.RenameField(
            model_name="compasdatasetmodel",
            old_name="files",
            new_name="file",
        ),
    ]
