# Generated by Django 3.2.13 on 2022-08-12 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_auto_20220516_0232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compasmodel',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='compaspublication',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ['tag']},
        ),
    ]
