# Generated by Django 3.2.13 on 2023-02-06 00:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0005_auto_20220823_0631"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompasDatasetModelUploadToken",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("user_id", models.IntegerField()),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.AlterField(
            model_name="compasdatasetmodel",
            name="compas_publication",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dataset_models",
                to="publications.compaspublication",
            ),
        ),
    ]
